// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.service1;

public interface ResponseMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.ResponseMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 length = 1;</code>
   */
  int getLength();
}
