// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service4.proto

package ds.service4;

public interface RequestMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service4.RequestMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
